object Versions {
    const val kotlin = "1.4.10"
    const val ktor = "1.4.2"
    const val logback = "1.2.3"
    const val kotlinxSerialization = "1.0.1"
    const val fritz2Gradle = "0.7.1"
    const val androidGradlePlugin = "4.1.1"
    const val coroutines = "1.4.1"
    const val coreKtx = "1.3.2"
    const val lifecycle = "2.2.0"
    const val material = "1.2.1"
    const val appCompat = "1.2.0"
    const val constraintLayout = "2.0.4"
    const val fragment = "1.2.4"
    const val flowbinding = "1.0.0-beta02"
}
